-- MySQL Script generated by MySQL Workbench
-- 12/06/15 17:55:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dwtf_db
-- -----------------------------------------------------
-- Trabalho Final - Data Warehouse UFSC

-- -----------------------------------------------------
-- Schema dwtf_db
--
-- Trabalho Final - Data Warehouse UFSC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dwtf_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dwtf_db` ;

-- -----------------------------------------------------
-- Table `dwtf_db`.`dm_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwtf_db`.`dm_evento` (
  `seq_evento` INT NOT NULL COMMENT '',
  `cod_evento` INT NOT NULL COMMENT '',
  `ano` INT NULL COMMENT '',
  `descricao` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`seq_evento`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwtf_db`.`dm_candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwtf_db`.`dm_candidato` (
  `seq_candidato` INT NOT NULL COMMENT '',
  `cod_candidato` INT NULL COMMENT '',
  `opcao` CHAR(3) NULL COMMENT '',
  `sexo` CHAR(9) NULL COMMENT '',
  `trabalha` VARCHAR(12) NULL COMMENT '',
  `pre_vest` VARCHAR(25) NULL COMMENT '',
  `idade` INT NULL COMMENT '',
  PRIMARY KEY (`seq_candidato`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwtf_db`.`dm_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwtf_db`.`dm_curso` (
  `seq_curso` INT NOT NULL COMMENT '',
  `cod_curso` INT NOT NULL COMMENT '',
  `nome` VARCHAR(100) NULL COMMENT '',
  `centro` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`seq_curso`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwtf_db`.`dm_socioeconomico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwtf_db`.`dm_socioeconomico` (
  `seq_socioeconomico` INT NOT NULL COMMENT '',
  `cod_candidato` INT NOT NULL COMMENT '',
  `faixa_etaria` VARCHAR(45) NULL COMMENT '',
  `renda_familiar` VARCHAR(30) NULL COMMENT '',
  PRIMARY KEY (`seq_socioeconomico`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwtf_db`.`dm_regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwtf_db`.`dm_regiao` (
  `seq_regiao` INT NOT NULL COMMENT '',
  `cod_candidato` INT NOT NULL COMMENT '',
  `pais` VARCHAR(6) NULL COMMENT '',
  `estado` VARCHAR(2) NULL COMMENT '',
  `cidade` VARCHAR(40) NULL COMMENT '',
  `bairro` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`seq_regiao`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwtf_db`.`ft_desempenho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwtf_db`.`ft_desempenho` (
  `seq_desempenho` INT NOT NULL COMMENT '',
  `seq_evento` INT NOT NULL COMMENT '',
  `seq_curso` INT NOT NULL COMMENT '',
  `seq_candidato` INT NOT NULL COMMENT '',
  `seq_socioeconomico` INT NOT NULL COMMENT '',
  `seq_regiao` INT NOT NULL COMMENT '',
  `aprovado` INT NULL COMMENT '',
  `nota_geral` DECIMAL(5,2) NULL COMMENT '',
  `total_exatas` DOUBLE NULL COMMENT '',
  `total_humanas` DOUBLE NULL COMMENT '',
  `nota_matematica` DECIMAL(5,2) NULL COMMENT '',
  `nota_lingua_estrangeira` DECIMAL(5,2) NULL COMMENT '',
  `nota_fisica` DECIMAL(5,2) NULL COMMENT '',
  `nota_quimica` DECIMAL(5,2) NULL COMMENT '',
  `nota_biologia` DECIMAL(5,2) NULL COMMENT '',
  PRIMARY KEY (`seq_desempenho`, `seq_evento`, `seq_curso`, `seq_candidato`, `seq_socioeconomico`, `seq_regiao`)  COMMENT '',
  INDEX `fk_ft_desempenho_dm_evento_idx` (`seq_evento` ASC)  COMMENT '',
  INDEX `fk_ft_desempenho_dm_curso1_idx` (`seq_curso` ASC)  COMMENT '',
  INDEX `fk_ft_desempenho_dm_candidato1_idx` (`seq_candidato` ASC)  COMMENT '',
  INDEX `fk_ft_desempenho_dm_socioeconomico1_idx` (`seq_socioeconomico` ASC)  COMMENT '',
  INDEX `fk_ft_desempenho_dm_regiao1_idx` (`seq_regiao` ASC)  COMMENT '',
  CONSTRAINT `fk_ft_desempenho_dm_evento`
    FOREIGN KEY (`seq_evento`)
    REFERENCES `dwtf_db`.`dm_evento` (`seq_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ft_desempenho_dm_curso1`
    FOREIGN KEY (`seq_curso`)
    REFERENCES `dwtf_db`.`dm_curso` (`seq_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ft_desempenho_dm_candidato1`
    FOREIGN KEY (`seq_candidato`)
    REFERENCES `dwtf_db`.`dm_candidato` (`seq_candidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ft_desempenho_dm_socioeconomico1`
    FOREIGN KEY (`seq_socioeconomico`)
    REFERENCES `dwtf_db`.`dm_socioeconomico` (`seq_socioeconomico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ft_desempenho_dm_regiao1`
    FOREIGN KEY (`seq_regiao`)
    REFERENCES `dwtf_db`.`dm_regiao` (`seq_regiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
